### ISSUE TITLE
Replace AssertionError raised for a particular unreachable reflection with something useful to users

### ISSUE THREAD

**Issue by robwalton** [DiamondLightSource/diffcalc#30]
```
>>>ub
UBCALC

   name:      mt8877-1

CRYSTAL

   name:          GaAs

   a, b, c:    5.65325   5.65325   5.65325
              90.00000  90.00000  90.00000

   B matrix:   1.11143  -0.00000  -0.00000
               0.00000   1.11143  -0.00000
               0.00000   0.00000   1.11143

UB MATRIX

   U matrix:  -0.71022   0.70390   0.01071
              -0.39941  -0.41543   0.81725
               0.57971   0.57615   0.57618

   UB matrix: -0.78935   0.78234   0.01191
              -0.44391  -0.46172   0.90831
               0.64431   0.64034   0.64039

REFLECTIONS

     ENERGY     H     K     L       PHI      CHI      ETA       MU    DELTA      GAM  TAG
   1 10.000  1.00  1.00  1.00   90.0000  89.9200  10.8220  -0.0000  21.9350  -0.0000  
   2 10.000  0.00  0.00  2.00   88.6700  35.4098  13.1400   0.0000  25.3376   0.0000  



>>>con qaz 90 alpha 5 mu 0
    qaz: 90.0000
    alpha: 5.0000
    mu: 0.0000

>>>sim hkl [1 1 1]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/util.py", line 346, in wrapper
    return call_command(f, args)
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/util.py", line 356, in call_command
    return f(*args)
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/util.py", line 356, in call_command
    return f(*args)
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/diffcalc_.py", line 267, in sim
    print scn.simulateMoveTo(hkl)
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/diffcalc_.py", line 267, in sim
    print scn.simulateMoveTo(hkl)
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/gdasupport/scannable/hkl.py", line 103, in simulateMoveTo
    (pos, params) = self._diffcalc.hkl_to_angles(hkl[0], hkl[1], hkl[2])
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/diffcalc_.py", line 205, in hkl_to_angles
    (pos, params) = self._hklcalc.hklToAngles(h, k, l, wavelength)
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/hkl/you/calc.py", line 316, in hklToAngles
    pos_virtual_angles_pairs = self._hklToAngles(h, k, l, wavelength)  # in rad
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/hkl/you/calc.py", line 384, in _hklToAngles
    psi, alpha, _ = self._calc_remaining_reference_angles(
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/hkl/you/calc.py", line 503, in _calc_remaining_reference_angles
    psi = acos(bound(cos_psi))
  File "/dls_sw/i16/software/gda_versions/gda_8.30/workspace_git/diffcalc.git/diffcalc/util.py", line 120, in bound
    raise AssertionError(
AssertionError: The value (23.058411) was unexpectedly too far outside -1 or 1 to safely bound. Please report this.
```

**Comment by isikhar** [comment]
```In [21]: ub
UBCALC     

   name:          GaAs

   n_phi:      0.00000   0.00000   1.00000 <- set
   n_hkl:      0.57971   0.57615   0.57618       
   normal:     None                              

CRYSTAL

   name:          GaAs

   a, b, c:    5.65325   5.65325   5.65325
              90.00000  90.00000  90.00000

   B matrix:   1.11143   0.00000   0.00000
               0.00000   1.11143   0.00000
               0.00000   0.00000   1.11143

UB MATRIX

   U matrix:  -0.71022   0.70390   0.01071
              -0.39941  -0.41543   0.81725
               0.57971   0.57615   0.57618

   miscut:
      angle:  54.81738
       axis:  -0.99991   0.01311   0.00000

   UB matrix: -0.78935   0.78234   0.01191
              -0.44391  -0.46172   0.90831
               0.64431   0.64034   0.64039

REFLECTIONS

     ENERGY     H     K     L        MU    DELTA      GAM      ETA      CHI      PHI  TAG
   1 10.000  1.00  1.00  1.00    0.0000  21.9350   0.0000  10.8220  89.9200  90.0000  None
   2 10.000  0.00  0.00  2.00    0.0000  25.3376   0.0000  13.1400  35.4098  88.6700  None

CRYSTAL ORIENTATIONS

   <<< none specified >>>

In [22]: sim hkl [1 1 1]
---------------------------------------------------------------------------
DiffcalcException                         Traceback (most recent call last)
<ipython-input-22-4d3e0416929e> in <module>()                              
----> 1 get_ipython().magic(u'sim hkl [1 1 1]')                            

/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')                                                        
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)                                                      
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159
   2160     #-------------------------------------------------------------------------

/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081

/dls_sw/apps/diffcalc/proto/diffcalc/diffcmd/ipython.pyc in wrapper(line)
    207     def wrapper(line):
    208         args = parse(line, global_namespace_dict)
--> 209         return f(*args)
    210     return wrapper
    211

/dls_sw/apps/diffcalc/proto/diffcalc/diffcalc/gdasupport/scannable/sim.pyc in sim(scn, hkl)
     16
     17     try:
---> 18         print scn.simulateMoveTo(hkl)
     19     except AttributeError:
     20         raise TypeError(

/dls_sw/apps/diffcalc/proto/diffcalc/diffcalc/gdasupport/scannable/hkl.pyc in simulateMoveTo(self, hkl)
    103         if len(hkl) != 3:
    104             raise ValueError('Hkl device expects three inputs')
--> 105         (pos, params) = self._diffcalc.hkl_to_angles(hkl[0], hkl[1], hkl[2])
    106
    107         width = max(len(k) for k in (params.keys() + list(self.diffhw.getInputNames())))

/dls_sw/apps/diffcalc/proto/diffcalc/diffcalc/dc/dcyou.pyc in hkl_to_angles(h, k, l, energy)
     31         energy = settings.hardware.get_energy()  # @UndefinedVariable
     32
---> 33     (pos, params) = hklcalc.hklToAngles(h, k, l, energy_to_wavelength(energy))
     34     angle_tuple = settings.geometry.internal_position_to_physical_angles(pos)  # @UndefinedVariable
     35     angle_tuple = settings.hardware.cut_angles(angle_tuple)  # @UndefinedVariable

/dls_sw/apps/diffcalc/proto/diffcalc/diffcalc/hkl/you/calc.pyc in hklToAngles(self, h, k, l, wavelength, return_all_solutions)
    293         """
    294
--> 295         pos_virtual_angles_pairs = self._hklToAngles(h, k, l, wavelength, return_all_solutions)  # in rad
    296         assert pos_virtual_angles_pairs
    297         pos_virtual_angles_pairs_in_degrees = []

/dls_sw/apps/diffcalc/proto/diffcalc/diffcalc/hkl/you/calc.pyc in _hklToAngles(self, h, k, l, wavelength, return_all_solutions)
    407
    408         if not solution_tuples:
--> 409             raise DiffcalcException('No solutions were found. '
    410                 'Please consider using an alternative set of constraints.')
    411

DiffcalcException:

***********************************************************************************
* No solutions were found. Please consider using an alternative set of constraints.
***********************************************************************************
```
