### ISSUE TITLE
I21 'sa' scannable failed with 'No Child named:formatPositionFields when running in GDA

### ISSUE THREAD

**Issue by fajinyuan** [DiamondLightSource/diffcalc#38]
```
>>> sa
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/beamlinespecific/i21.py", line 132, in __repr__
    formatted_values = self.formatPositionFields(pos)
  File "/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/diffcalc/gdasupport/minigda/scannable.py", line 408, in __getattr__
    raise AttributeError("No child named:" + name)
AttributeError: No child named:formatPositionFields
```

**Comment by fajinyuan** [comment]
GDA ScannableBase does not have this method 'formatPositionFields(pos)', however this method is present in ScannableBase class in scannable.py in diffcalc.

**Comment by fajinyuan** [comment]
refactor this method and its calling method to a child class that implemented only in python/jython, this way no Java change will be needed and IPython will not be affected.

**Comment by fajinyuan** [comment]
move formatPositionFields(pos) and its calling method from ScannableBase to ScannableMotionWithScannableFieldsBase

test results:
```
>>> sa
sa:                            
sapolar:   2.00000 (eta)       tp_phi :  0.0000  0.0000  0.0000 (set)
satilt:    90.00000 (chi-90)   tp_lab :  0.0000  0.0000  0.0000
saazimuth: 185.73871 (phi)     xyz_eta:  0.0000  0.0000  0.0000

For help with sa, tp_phi and tp_lab see: http://confluence.diamond.ac.uk/x/CBIAB

```
