### ISSUE TITLE
tp_lab throw exception - null

### ISSUE THREAD

**Issue by fajinyuan** [DiamondLightSource/diffcalc#40]
```
2017-08-09 15:36:15,263 DEBUG [RequestProcessor-4] gda.jython.logger.RedirectableFileLogger -  | >>> tp_lab  
2017-08-09 15:36:15,264 DEBUG [logback-1] gda.jython.GDAInteractiveConsole - GDA command: tp_lab  
2017-08-09 15:36:15,264 DEBUG [logback-1] gda.jython.GDAInteractiveConsole - Jython command: tp_lab  
2017-08-09 15:36:15,280 DEBUG [2017-08-09T15:36:15 : tp_lab] gda.jython.logger.RedirectableFileLogger -  | Traceback (most recent call last):  
2017-08-09 15:36:15,280 DEBUG [2017-08-09T15:36:15 : tp_lab] gda.jython.logger.RedirectableFileLogger -  |   File '<input>', line 1, in <module>  
2017-08-09 15:36:15,280 DEBUG [2017-08-09T15:36:15 : tp_lab] gda.jython.logger.RedirectableFileLogger -  |   File '/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/diffcalc/gdasupport/minigda/scannable.py', line 324, in __repr__  
2017-08-09 15:36:15,280 DEBUG [2017-08-09T15:36:15 : tp_lab] gda.jython.logger.RedirectableFileLogger -  |     pos = self.getPosition()  
2017-08-09 15:36:15,282 DEBUG [2017-08-09T15:36:15 : tp_lab] gda.jython.logger.RedirectableFileLogger -  | gda.device.DeviceException: exception in tp_lab.getPosition()  
2017-08-09 15:36:15,283 ERROR [logback-1] gda.jython.GDAInteractiveConsole - InteractiveConsole exception: exception in tp_lab.getPosition() org.python.core.PyException: null
	at org.python.core.Py.JavaError(Py.java:548)
	at org.python.core.Py.JavaError(Py.java:539)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at diffcalc.gdasupport.minigda.scannable$py.__repr__$62(/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/diffcalc/gdasupport/minigda/scannable.py:334)
	at diffcalc.gdasupport.minigda.scannable$py.call_function(/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/diffcalc/gdasupport/minigda/scannable.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.core.PyMethod.__call__(PyMethod.java:117)
	at org.python.core.PyObjectDerived.__repr__(PyObjectDerived.java:104)
	at org.python.core.PySystemState.displayhook(PySystemState.java:1438)
	at org.python.core.PySystemStateFunctions.__call__(PySystemState.java:1804)
	at org.python.core.PyObject.invoke(PyObject.java:3728)
	at org.python.core.Py.printResult(Py.java:2053)
	at org.python.pycode._pyx577.f$0(<input>:1)
	at org.python.pycode._pyx577.call_function(<input>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1401)
	at org.python.core.Py.exec(Py.java:1445)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at org.python.util.InteractiveInterpreter.runcode(InteractiveInterpreter.java:131)
	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:116)
	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:50)
	at gda.jython.GDAInteractiveConsole.runsource(GDAInteractiveConsole.java:111)
	at gda.jython.GDAJythonInterpreter.runsource(GDAJythonInterpreter.java:632)
	at gda.jython.JythonServer$RunSourceRunner.run(JythonServer.java:1350)
Caused by: gda.device.DeviceException: exception in tp_lab.getPosition()
	at gda.device.scannable.ScannableBase.getPosition(ScannableBase.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	... 29 common frames omitted
Caused by: org.python.core.PyException: null
	at org.python.core.Py.TypeError(Py.java:261)
	at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:209)
	at org.python.core.PyReflectedFunction.throwBadArgError(PyReflectedFunction.java:312)
	at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:321)
	at org.python.core.PyReflectedConstructor.__call__(PyReflectedConstructor.java:177)
	at org.python.core.PyObject.__call__(PyObject.java:438)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1700)
	at org.python.core.PyType.__call__(PyType.java:1683)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
	at numjy.jama_matrix_wrapper$py.__init__$2(/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/numjy/jama_matrix_wrapper.py:44)
	at numjy.jama_matrix_wrapper$py.call_function(/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/numjy/jama_matrix_wrapper.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1700)
	at org.python.core.PyType.__call__(PyType.java:1683)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
	at startup.beamlinespecific.i21$py.calc_tp_lab$1(/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/beamlinespecific/i21.py:51)
	at startup.beamlinespecific.i21$py.call_function(/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/beamlinespecific/i21.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
	at org.python.core.PyFunction.function___call__(PyFunction.java:471)
	at org.python.core.PyFunction.__call__(PyFunction.java:466)
	at org.python.core.PyFunction.__call__(PyFunction.java:456)
	at startup.beamlinespecific.i21$py.rawGetPosition$34(/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/beamlinespecific/i21.py:321)
	at startup.beamlinespecific.i21$py.call_function(/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/beamlinespecific/i21.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3645)
	at org.python.proxies.startup.beamlinespecific.i21$I21TPLab$79.rawGetPosition(Unknown Source)
	at gda.device.scannable.ScannableBase.getPosition(ScannableBase.java:186)
	... 34 common frames omitted
 
```

**Comment by fajinyuan** [comment]
Inside GDA the Scannable.getPosition() returns a Java Array, which have to be converted to a jython list before sending to calc_tp_lab(...) to create a matrix using Jama.Matrix.
