### ISSUE TITLE
'pos tp_lab [1 2 3]' command failed inside GDA

### ISSUE THREAD

**Issue by fajinyuan** [DiamondLightSource/diffcalc#41]
>>> pos tp_lab [1 2 3]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/beamlinespecific/i21.py", line 330, in waitWhileBusy
    self.self.sample_stage_scn.xyz_eta_scn.waitWhileBusy()
  File "/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/diffcalc/gdasupport/minigda/scannable.py", line 408, in __getattr__
    raise AttributeError("No child named:" + name)
AttributeError: No child named:self

**Comment by fajinyuan** [comment]
find the mistake introduced in commit 6f6e08d5c74a22fba87b2a42894e8bbcccdddb8d

**Comment by fajinyuan** [comment]
committed fc14fa63055a34c9135d30246a79b2870cb48934
