### ISSUE TITLE
zerosample failed.

### ISSUE THREAD

**Issue by fajinyuan** [DiamondLightSource/diffcalc#42]
```
>>> zerosample
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/i21.py", line 55, in zerosample
    sa.zerosample()
  File "/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/beamlinespecific/i21.py", line 194, in zerosample
    tp_phi = move_lab_origin_into_phi(chi, phi, xyz_eta_tuple)
  File "/scratch/gda_versions/gda_master2/workspace_git/diffcalc.git/startup/beamlinespecific/i21.py", line 63, in move_lab_origin_into_phi
    tp_phi = PHI.I * CHI.I * (-1 * xyz_eta)
TypeError: unsupported operand type(s) for *: 'int' and 'matrix'
```

**Comment by fajinyuan** [comment]
a workaround provided for now.

**Comment by fajinyuan** [comment]
commit 678b3bcbbadce5a48d483bdf618b01af542ed7fd
